# Generated by Django 3.0.3 on 2020-03-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsnba', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='fg',
            new_name='fg_p',
        ),
        migrations.AddField(
            model_name='player',
            name='tp_p',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
            preserve_default=False,
        ),
    ]
