# Generated by Django 3.0.3 on 2020-03-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsnba', '0002_auto_20200304_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='fg_p',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
