# Generated by Django 3.0.4 on 2020-04-03 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsnba', '0003_auto_20200304_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
